// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResumeDBContext))]
    [Migration("20260725211717_RenameColumnNamesForPersonalDetails")]
    partial class RenameColumnNamesForPersonalDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PersonalDetails", "Domain.Resume.PersonalDetails#PersonalDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .HasColumnType("text")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<string>("FirstName")
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("JobTitle")
                                .HasColumnType("text")
                                .HasColumnName("job_title");

                            b1.Property<string>("LastName")
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("phone");

                            b1.Property<string>("Photo")
                                .HasColumnType("text")
                                .HasColumnName("photo");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text")
                                .HasColumnName("postal_code");
                        });

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.ToTable("resumes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
